# Generated by Django 2.1.5 on 2019-02-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0003_auto_20190218_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='asset_details',
            field=models.CharField(max_length=200),
        ),
    ]
