# Generated by Django 2.1.5 on 2019-02-20 06:00

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_lastname', models.CharField(max_length=100)),
                ('Registration_date', models.DateField(null=True)),
                ('class_name', models.CharField(choices=[('lkg', 'LKG'), ('ukg', 'UKG'), ('I Standard', 'I STANDARD'), ('II Standard', 'II STANDARD'), ('III Standard', 'III STANDARD'), ('IV Standard', 'IV STANDARD'), ('V Standard', 'V STANDARD'), ('VI Standard', 'VI STANDARD'), ('VII Standard', 'VII STANDARD'), ('VIII Standard', 'VIII STANDARD'), ('IX Standard', 'IX STANDARD'), ('X Standard', 'X STANDARD')], max_length=30)),
                ('gender_type', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=30)),
                ('mob_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('parents_name', models.CharField(max_length=100)),
                ('parents_phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('Birth_date', models.DateField(null=True)),
                ('Blood_group', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('rti', models.BooleanField(default=False)),
                ('sibling', models.BooleanField(default=False)),
                ('sib_class_name', models.CharField(choices=[('lkg', 'LKG'), ('ukg', 'UKG'), ('I Standard', 'I STANDARD'), ('II Standard', 'II STANDARD'), ('III Standard', 'III STANDARD'), ('IV Standard', 'IV STANDARD'), ('V Standard', 'V STANDARD'), ('VI Standard', 'VI STANDARD'), ('VII Standard', 'VII STANDARD'), ('VIII Standard', 'VIII STANDARD'), ('IX Standard', 'IX STANDARD'), ('X Standard', 'X STANDARD')], max_length=30)),
                ('sib_rel_name', models.CharField(choices=[('Brother', 'LKG'), ('Sister', 'UKG')], max_length=30)),
                ('sib_phone', phone_field.models.PhoneField(blank=True, help_text='Sibling Contact phone number', max_length=31)),
                ('sib_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Monthly', 'Monthly'), ('yearly', 'yearly'), ('session', 'session')], max_length=50)),
                ('fees_amount', models.CharField(max_length=50)),
                ('ref_number', models.CharField(max_length=50)),
                ('pay_type', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online Transfer', 'Online Transfer'), ('Sister', 'UKG'), ('Sister', 'UKG')], max_length=30)),
                ('pay_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Pending', 'Pending')], max_length=30)),
                ('pay_details', models.CharField(max_length=50)),
            ],
        ),
    ]
