# Generated by Django 2.1.5 on 2019-02-20 06:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mob_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='parents_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='pay_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online Transfer', 'Online Transfer'), ('Draft', 'Draft'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='sib_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Sibling Contact phone number', max_length=128),
        ),
    ]
