# Generated by Django 2.1.5 on 2019-02-20 12:34

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_auto_20190220_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mob_number',
            field=phone_field.models.PhoneField(max_length=31),
        ),
        migrations.AlterField(
            model_name='student',
            name='parents_phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
        migrations.AlterField(
            model_name='student',
            name='sib_phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
        migrations.AlterField(
            model_name='student',
            name='sib_rel_name',
            field=models.CharField(choices=[('Brother', 'Brother'), ('Sister', 'Sister')], max_length=30),
        ),
    ]
